# Generated by Django 4.2.3 on 2023-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquina/'),
        ),
    ]
