# Generated by Django 4.2.3 on 2023-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_maquina_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='maquinas',
            field=models.ManyToManyField(to='biblioteca.maquina'),
        ),
    ]
